# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - kpop-nickel-web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Create strapi-app
        run: yarn create strapi-app kpop-nickel --dbclient=mysql --dbhost=strapi --dbport=3306 --dbname=strapi --dbusername=strapi --dbpassword=strapi --no-run

      - name: Prepare application
        run: |
          sed -i 's!strapi start!node node_modules/@strapi/strapi/bin/strapi.js start!g' kpop-nickel/package.json
          cp -R config_override/*.js kpop-nickel/config

      - name: Install dependencies
        run: |
          export NODE_ENV=production SITE_URL=${{ secrets.SITE_URL }}
          yarn install --cwd=kpop-nickel
          cd kpop-nickel && yarn build

      - name: Zip files
        run: cd kpop-nickel && zip -qyr ../node-app.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: node-app.zip

      - name: Build standalone development admin panel
        run: export NODE_ENV=development SITE_URL=${{ secrets.SITE_URL }}

      - name: Zip files
        run: cd kpop-nickel/build && zip -qyr ../node-app-admin.zip .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      #- name: 'Untar files'
      #  run: 'tar -zxf node-app.tar.gz'

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'kpop-nickel-web'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4E9D0F74E7054D46B86E5953DF278681 }}
          package: node-app.zip
