# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - kpop-nickel-web

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DEPLOY_FRONTEND: false
  DEPLOY_ADMIN: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Create strapi-app
        run: yarn create strapi-app kpop-nickel --dbclient=mysql --dbhost=strapi --dbport=3306 --dbname=strapi --dbusername=strapi --dbpassword=strapi --no-run

      - name: Prepare application
        run: |
          sed -i 's!strapi start!node node_modules/@strapi/strapi/bin/strapi.js start!g' kpop-nickel/package.json
          cp -R config_override/*.js kpop-nickel/config

      - name: Install dependencies
        run: |
          yarn install --cwd=kpop-nickel
          cd kpop-nickel && yarn build
        env:
          NODE_ENV: production
          SITE_URL: ${{ secrets.SITE_URL }}
        if: ${{ env.DEPLOY_FRONTEND }}

      - name: Zip app files
        run: cd kpop-nickel && zip -qyr ../node-app.zip .
        if: ${{ env.DEPLOY_FRONTEND }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: node-app.zip
        if: ${{ env.DEPLOY_FRONTEND }}

      - name: Build standalone development admin panel
        run: cd kpop-nickel && yarn build
        env:
          NODE_ENV: development
          SITE_URL: ${{ secrets.SITE_URL }}
        if: ${{ env.DEPLOY_ADMIN }}

      - name: Zip admin panel files
        run: cd kpop-nickel/build && zip -qyr ../../node-app-admin.zip .
        if: ${{ false }}
        
      - name: Deploy admin panel
        id: admindeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WONDERFUL_WAVE_05277EC0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          skip_app_build: true
          skip_api_build: true
          app_location: "kpop-nickel/build" # App source code path
          ###### End of Repository/Build Configurations ######
        if: ${{ env.DEPLOY_ADMIN }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      #- name: 'Untar files'
      #  run: 'tar -zxf node-app.tar.gz'

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'kpop-nickel-web'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4E9D0F74E7054D46B86E5953DF278681 }}
          package: node-app.zip
